version: 17
jobs:
- name: Push to Github
  jobExecutor: root-executor
  steps:
  - !PushRepository
    name: Github
    remoteUrl: https://github.com/watzon/safety.git
    userName: watzon
    passwordSecret: access-token
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Pull from Github
  jobExecutor: root-executor
  steps:
  - !PullRepository
    name: Pull from Github
    remoteUrl: https://github.com/watzon/safety.git
    userName: watzon
    passwordSecret: access-token
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !ScheduleTrigger
    cronExpression: 0 0 1 * * ?
    projects: safety
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
